# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls
          New-Item -Path . -Name "THUAI3.0" -ItemType "directory"
          ls
          cd ./logic
          ls
          ./build_logic.ps1 -Dir ../THUAI3.0
          ls
          cd ..
          ls
          (Get-Content "runServer.bat").replace("logic\Logic.Server\bin\Release\netcoreapp3.0","THUAI3.0") | Set-Content "runServer.bat"
          (Get-Content "runServerToFile.bat").replace("logic\Logic.Server\bin\Release\netcoreapp3.0","THUAI3.0") | Set-Content "runServerToFile.bat"
          (Get-Content "runAgent.bat").replace("communication\Agent\bin\Release\netcoreapp3.0","THUAI3.0") | Set-Content "runAgent.bat"
          (Get-Content "runClientConsole.bat").replace("logic\Logic.Client\bin\Release\netcoreapp3.0","THUAI3.0") | Set-Content "runClientConsole.bat"
          python ./upload_to_tencent_cloud.py --id ${{ secrets.TENCENT_CLOUD_ID }} --key ${{ secrets.TENCENT_CLOUD_KEY }} CAPI THUAI3.0 Config runServer.bat runServerToFile.bat runAgent.bat runClientConsole.bat API.md README.md
